name: WiLoR-mini
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pip:
    - tqdm
    - opencv-python
    - git+https://github.com/warmshao/WiLoR-mini
